version: '3.8'

services:
  rtscommander:
    build: .
    container_name: rtscommander
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./remotes.json:/root/config/remotes.json
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
    privileged: true
    environment:
      - TZ=Europe/Paris
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
